const head = [
  {
    id: "srNo",
    label: "Sr.No",
    minWidth: 50,
    width: 50,
    maxWidth: 50,
    align: "center",
  },
  {
    id: "fileName",
    label: "File Name",
    minWidth: 140,
    width: 140,
    maxWidth: 140,
    align: "center",
  },
  {
    id: "playAudio",
    label: "Play Audio",
    minWidth: 40,
    width: 40,
    maxWidth: 40,
    align: "center",
  },
  {
    id: "date",
    label: "Date",
    minWidth: 140,
    width: 140,
    maxWidth: 140,
    align: "center",
  },
  {
    id: "audioFile",
    label: "Call Duration (s)",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
  {
    id: "agentName",
    label: "Name",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
    // format: (value) => value.toLocaleString('en-US'),
  },

  {
    id: "agentSentimentType",
    label: "Sentiment",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
  {
    id: "agentSentimentScore",
    label: "Sentiment Score",
    minWidth: 130,
    width: 130,
    maxWidth: 130,
    align: "center",
  },
  {
    id: "agentSubjectivity",
    label: "Subjectivity",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
  {
    id: "customerName",
    label: "Name",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
    // format: (value) => value.toLocaleString('en-US'),
  },

  {
    id: "customerSentimentType",
    label: "Sentiment",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
  {
    id: "customerSentimentScore",
    label: "Sentiment Score",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
  {
    id: "customerSubjectivity",
    label: "Subjectivity",
    minWidth: 100,
    width: 100,
    maxWidth: 100,
    align: "center",
  },
];

export default head;
